FROM node:20 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20

ENV NODE_ENV=production

COPY package*.json ./

RUN npm install

COPY --from=build /app/dist dist

EXPOSE 3000

CMD ["npm", "start"]