name: Deploy Chat App

on: push

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Backend
        working-directory: ./backend
        run: |
          npm ci
          npm install
          npm run build -- --verbose
          #npm test

          echo "=== Checking Models ==="
          ls -la src/models/
          echo "=== Compiled Files ==="
          ls -la dist/

      - name: Setup Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
        #   npm test

      - name: Deploy
        run: |
          echo "deployed"
        # add deployment cmds
